### ISSUE TITLE
rust-mos resources

### ISSUE THREAD

**Issue by ghost** [mrk-its/rust-mos#5]
Any resources available we can use to help write/convert code to work with rust-mos?

I found https://github.com/mrk-its/mos-alloc, and that seems to help with Strings and hashmaps.  Any other resources?

BTW, thank you..  great project!

**Comment by mrk-its** [comment]
There are some:
* [ufmt](https://crates.io/crates/ufmt) & [ufmt-stdio](https://crates.io/crates/ufmt-stdio) crates - they provide lighter formatting & `println!` macro. ufmt-stdio works because it has [builtin support](https://github.com/DoumanAsh/ufmt-stdio/commit/ab5a0f5726b3f1546b0430a66920962249167990) for mos arch already :) 
* for atari8 I created [a800xl-utils](https://crates.io/crates/a800xl-utils) crate ([docs](https://docs.rs/a800xl-utils/latest/a800xl_utils/))
* [mos-alloc](https://crates.io/crates/mos-alloc) crate (mentioned by you above)
* recently while porting more [aoc2021](https://github.com/mrk-its/aoc2021) solutions to rust-mos I created simple implementation of [Pearson hashing](https://github.com/mrk-its/aoc2021/blob/master/utils/src/hash.rs) and created very simple HashMap / HashSet [implementations](https://github.com/mrk-its/aoc2021/blob/master/utils/src/lib.rs#L96) - but there should be more sensible alternatives for that already on crates.io

**Comment by mlund** [comment]
See also the "Other resources" at the llvm-mos wiki page about rust: https://llvm-mos.org/wiki/Rust

**Comment by mrk-its** [comment]
Thanks @mlund! I didn't notice you started work on Rust page on llvm-mos wiki, good job!

**Comment by mlund** [comment]
> Thanks @mlund! I didn't notice you started work on Rust page on llvm-mos wiki, good job!

well, thank you - I have had lots of fun with rust-mos! 😊
